### ISSUE TITLE
Support for grouped checkboxes

### ISSUE THREAD

**Issue by RickGeersing** [fawaz-alesayi/svelte-use-presist#10]
Nice package, works like a charm on most points. The only thing I am missing is the support for bundled checkboxes. Right now if the checkbox has multiple values, only the first entry is persisted to localstorage. Would be nice to have.

**Comment by RickGeersing** [comment]
https://github.com/fawaz-alesayi/svelte-use-persist/pull/11

**Comment by fawaz-alesayi** [comment]
Closed by #11
Thanks
